openapi: 3.0.3
info:
  title: API Ping
  description: Une API simple qui retourne pong pour tester la disponibilité.
  version: 1.0.0

paths:
  /ping:
    get:
      summary: Vérifie la disponibilité de l'API
      responses:
        '200':
          description: Réponse avec pong
          content:
            text/plain:
              schema:
                type: string
                example: pong

