openapi: 3.0.3
info:
  title: API Users
  description: API de gestion des utilisateurs avec paramètres de pagination
  version: 1.0.0

paths:
  /users:
    get:
      summary: Récupère une liste d'utilisateurs
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
          description: Numéro de page (commence à 1)
        - name: size
          in: query
          required: false
          schema:
            type: integer
            example: 20
          description: Nombre d'éléments par page
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Alice
                    email:
                      type: string
                      format: email
                      example: alice@example.com
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad types for provided query parameters

